### ISSUE TITLE
Hidden documents

### ISSUE THREAD

**Issue by hanamura** [hanamura/gulp-minisite#84]
It is handy if there is a document not for creating a page but just for representing a piece of data.

For example, you are making a releases page of an app.

document: `releases.yml`
```yml
...
releases:
  - version: 5.0.0
    date: 2017-03-01
    changes: ...
  - version: 4.1.2
    date: 2017-01-23
    changes: ...
  ...
```

template: `releases.njk`
```jinja
{% for release in page.releases %}
<div>
  <h1>{{ release.version }}</h1>
  <time>{{ release.date }}</time>
  <div>{{ release.changes|markdown }}</div>
</div>
{% endfor %}
```

When your app grows up and the page gets complicated, you separate releases into separated pages.

documents:
`releases/5.0.0.yml`
`releases/4.1.2.yml`
`releases/4.1.1.yml`
...
```yml
...
version: 5.0.0
date: 2017-03-01
changes: ...
```

template: `releases.njk`
```jinja
{% for release in page.collection %}
<div>
  <h1><a href="{{ release.path }}">{{ release.version }}</a></h1>
  <time>{{ release.date }}</time>
</div>
{% endfor %}
```

---

Hidden documents make this transition more natural.

Create separated documents from the beginning and prefix filename with `.`:
`releases/.5.0.0.yml`
`releases/.4.1.2.yml`
`releases/.4.1.1.yml`
...

These documents never create actual files but you can still access them from templates.

template: `releases.njk`
```jinja
{% for release in page.collection %}
<div>
  <h1>{{ release.version }}</h1>
  <time>{{ release.date }}</time>
  <div>{{ release.changes|markdown }}</div>
</div>
{% endfor %}
```

To separate them, unprefix `.` and add `<a>` in `releases.njk`.

## Naming rule

It have to be considered with draft feature #36.

`_.#001.foo.en.yml`
or
`._#001.foo.en.yml`
